package:
  name: streaming-receiver
  version: "{{ SETUPTOOLS_SCM_PRETEND_VERSION }}"

source:
  path: ../

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - streaming-receiver = app.main:main

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python <3.12
    - cython
    - setuptools-scm

  run:
    - python <3.12
    - numpy
    - h5py
    - pyyaml
    - pyzmq
    - uvicorn
    - fastapi
    - bitshuffle-python
    - cbor2
