package:
  name: streaming-receiver
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - streaming-receiver = app.main:main
    
requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - cython
    
  run:
    - python
    - numpy
    - h5py
    - pyyaml
    - pyzmq
    - uvicorn
    - fastapi
    - bitshuffle-python
