stages:
  - build
  - upload
  - container

default:
  image: docker.maxiv.lu.se/conda-build:latest
  tags: [kubernetes]

conda_build:
  stage: build
  script:
    - conda build  --output-folder=package ./recipe
  artifacts:
    paths:
      - package/linux-64/streaming-receiver*.conda
    expire_in: 1 week
